services:
  keyboard-shortcuts:
    build: 
      context: .
      dockerfile: Dockerfile
    image: node:18-alpine
    container_name: keyboard-shortcuts.web.app
    working_dir: /usr/src/keyboard-shortcuts
    env_file:
      - .env
    ports:
      - 9090:9090
      - 9005:9005
    volumes:
      - ./:/usr/src/keyboard-shortcuts:rw
    command: "yarn start --host 0.0.0.0"
